[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "brisingr"
description = "Small python script which provides aliases and utilities for commands I hate to type."
authors = [{name = "Julian Kirsch", email = "contact@juliankirsch.me"}]
version = "1.0.1"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1"
]

[project.scripts]
brisingr = "brisingr.cli:cli"
